docker build -t dongjoon/centos7-hdw centos7-hdw
docker build -t dongjoon/ubuntu12.04-hdw ubuntu12.04-hdw
docker build -t dongjoon/ubuntu15.10-hdw ubuntu15.10-hdw
docker build -t dongjoon/ubuntu16.04-hdw ubuntu16.04-hdw
docker build -t dongjoon/ubuntu16.04-dev ubuntu16.04-dev
docker build -t dongjoon/debian8-hdw debian8-hdw
docker build -t dongjoon/java7-hdw java7-hdw
docker build -t dongjoon/java8-hdw java8-hdw
docker build -t dongjoon/java9-test java9-test
